export const ACCEPTED_MATERIALS = new Set([
  'Grass',
  'GrassShort',
  'GrassLong',
  'GravelSmall',
  'GravelLarge',
  'GravelDeep',
  'DirtTrack',
  'SandstoneBrittle',
  'SandCompact',
  'SandWet',
  'SandLoose',
  'MudHard',
  'MudSoft',
]);
