import { makeStyles } from '@mui/styles';

import { baseStyle } from '../../../../base.styles';

export const styles = makeStyles({
  forms: {
    width: '100%',
    height: 'calc( 100% - 1.1vh)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    pointerEvents: 'none',
    zIndex: 3,
    borderRadius: '1rem',
    '& > div': {
      minWidth: '80%',
      maxWidth: '80%',
      minHeight: '40%',
      maxHeight: '80%',
      overflow: 'scroll',
      padding: '.5vh .5vw',
      color: baseStyle.gray.lighter,
      backgroundColor: baseStyle.primaryDarker.dark,
      borderBottom: `.4vh solid ${baseStyle.gray.lighter}`,
      boxShadow: '0px 3px 5px 0px black',
      borderRadius: '1vh',
      pointerEvents: 'all',
      '& > *': {
        margin: '0 auto',
      },
    },
  },
  checkmarkWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmark: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    display: 'block',
    strokeWidth: '2',
    strokeMiterlimit: '10',
    margin: '10% auto',
    boxShadow: 'inset 0px 0px 0px #7ac142',
    animation: 'checkmark-fill 0.4s ease-in-out 0.4s forwards, checkmark-scale 0.3s ease-in-out 0.9s both',
    '& > .checkmark__check': {
      transformOrigin: '50% 50%',
      strokeDasharray: '48',
      strokeDashoffset: '48',
      stroke: '#fff',
      animation: 'checkmark-stroke 0.3s cubic-bezier(0.65, 0, 0.45, 1) 0.8s forwards',
    },
  },
  warningContainer: {
    display: 'flex',
    overflow: 'hidden',
    outline: 'none',
    width: '32em',
    padding: '1.25rem',
    margin: 'auto',
    borderRadius: '.3125em',
    textAlign: 'center',
    position: 'relative',
    flexDirection: 'column',
    justifyContent: 'center',
    maxWidth: '100%',
    zIndex: 5600,
  },
  warning: {
    width: 80,
    height: 80,
    borderWidth: 4,
    borderStyle: 'solid',
    borderRadius: '50%',
    margin: '20px auto',
    position: 'relative',
    boxSizing: 'content-box',
    borderColor: '#eea236',
    animation: 'pulseWarning 0.75s infinite alternate',
  },
  warningBody: {
    position: 'absolute',
    width: 5,
    height: 47,
    left: '50%',
    top: 10,
    borderRadius: 2,
    marginLeft: -2,
    backgroundColor: '#f0ad4e',
    animation: 'pulseWarningIns 0.75s infinite alternate',
  },
  warningDot: {
    position: 'absolute',
    width: 7,
    height: 7,
    borderRadius: '50%',
    marginLeft: -3,
    left: '50%',
    bottom: 10,
    backgroundColor: '#f0ad4e',
    animation: 'pulseWarningIns 0.75s infinite alternate',
  },
});
