ALTER TABLE business
  ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL DEFAULT '';

UPDATE business
SET name = 'dff'
WHERE id = 1;

ALTER TABLE business
  MODIFY COLUMN name VARCHAR(255) NOT NULL UNIQUE;

