export const BLACKLISTED_PED_MODELS = {
  s_m_y_ranger_01: { suppress: true, delete: true },
  s_f_y_ranger_01: { suppress: true, delete: true },
  s_m_y_sheriff_01: { suppress: true, delete: true },
  s_f_y_sheriff_01: { suppress: true, delete: true },
  s_m_y_cop_01: { suppress: true, delete: true },
  s_f_y_cop_01: { suppress: true, delete: true },
  s_m_y_hwaycop_01: { suppress: true, delete: true },
  s_m_y_armymech_01: { suppress: true, delete: true },
  s_m_m_marine_01: { suppress: true, delete: true },
  s_m_y_marine_01: { suppress: true, delete: true },
  s_m_m_marine_02: { suppress: true, delete: true },
  s_m_y_marine_02: { suppress: true, delete: true },
  s_m_y_marine_03: { suppress: true, delete: true },
  g_m_y_lost_02: { suppress: true, delete: true },
};

export const BLACKLISTED_VEHICLE_MODELS = {
  shamal: { suppress: true, delete: false }, // suppress but allowed for staff fso
  luxor: { suppress: true, delete: false }, // suppress but allowed for staff fso
  luxor2: { suppress: true, delete: false }, // suppress but allowed for staff fso
  jet: { suppress: true, delete: true },
  lazer: { suppress: true, delete: true },
  buzzard: { suppress: true, delete: true },
  buzzard2: { suppress: true, delete: true },
  annihilator: { suppress: true, delete: true },
  savage: { suppress: true, delete: true },
  titan: { suppress: true, delete: true },
  rhino: { suppress: true, delete: true },
  blimp: { suppress: true, delete: true },
  hydra: { suppress: true, delete: false }, // suppress but allowed for staff fso
  oppressor: { suppress: true, delete: true },
  technical3: { suppress: true, delete: false }, // suppress but allowed for staff fso
  insurgent3: { suppress: true, delete: true },
  apc: { suppress: true, delete: true },
  halftrack: { suppress: true, delete: true },
  hunter: { suppress: true, delete: true },
  vigilante: { suppress: true, delete: true },
  akula: { suppress: true, delete: true },
  barrage: { suppress: true, delete: true },
  khanjali: { suppress: true, delete: true },
  caracara: { suppress: true, delete: false }, // suppress but allowed for staff fso
  blimp3: { suppress: true, delete: true },
  menacer: { suppress: true, delete: true },
  oppressor2: { suppress: true, delete: true },
  scramjet: { suppress: true, delete: true },
  strikeforce: { suppress: true, delete: true },
  cerberus: { suppress: true, delete: true },
  cerberus2: { suppress: true, delete: true },
  cerberus3: { suppress: true, delete: true },
  scarab: { suppress: true, delete: true },
  scarab2: { suppress: true, delete: true },
  scarab3: { suppress: true, delete: true },
  ruiner2: { suppress: true, delete: true },
  deluxo: { suppress: true, delete: true },
  police: { suppress: true, delete: true },
  police2: { suppress: true, delete: true },
  police3: { suppress: true, delete: true },
  police4: { suppress: true, delete: true },
  policeb: { suppress: true, delete: true },
  policet: { suppress: true, delete: true },
  sheriff: { suppress: true, delete: true },
  sheriff2: { suppress: true, delete: true },
  polmav: { suppress: true, delete: true },
  cargobob: { suppress: true, delete: false }, // suppress but allowed for staff fso
  ambulance: { suppress: true, delete: true },
  skylift: { suppress: true, delete: true },
  cargobob2: { suppress: true, delete: true },
  valkyrie: { suppress: true, delete: true },
  annihilator2: { suppress: true, delete: true },
  handler: { suppress: true, delete: true },
  cutter: { suppress: true, delete: true },
  thruster: { suppress: true, delete: true },
  chernobog: { suppress: true, delete: true },
  minitank: { suppress: true, delete: true },
  kosatka: { suppress: true, delete: true },
  molotok: { suppress: true, delete: true },
  bombushka: { suppress: true, delete: true },
  howard: { suppress: true, delete: true },
  mogul: { suppress: true, delete: true },
  pyro: { suppress: true, delete: true },
  nokota: { suppress: true, delete: true },
  volatol: { suppress: true, delete: true },
  alkonost: { suppress: true, delete: true },
  cargoplane: { suppress: true, delete: true },
  miljet: { suppress: true, delete: false }, // suppress but allowed for staff fso
  blimp2: { suppress: true, delete: true },
  starling: { suppress: true, delete: true },
  rogue: { suppress: true, delete: true },
  tula: { suppress: true, delete: true },
  rcbandito: { suppress: true, delete: true },
  firetruk: { suppress: true, delete: true },
  besra: { suppress: true, delete: true },
  barracks2: { suppress: true, delete: true },
  barracks: { suppress: true, delete: true },
  tampa3: { suppress: true, delete: true },
  trailersmall2: { suppress: true, delete: true },
  dune3: { suppress: true, delete: true },
};
