version: 2

updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/Brussels"
    target-branch: "UPD"
    open-pull-requests-limit: 0
    directory: "/"
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/Brussels"
    target-branch: "UPD"
    open-pull-requests-limit: 0
    directory: "/resources/[dg]/dg-financials/typescript"
  - package-ecosystem: "npm"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/Brussels"
    target-branch: "UPD"
    open-pull-requests-limit: 0
    directory: "/resources/[dg]/dg-ui/[src]"
   