import './controllers';
import './modules/permissions';
import './modules/commands';
import './modules/whitelist';
import './modules/menu';
import './modules/penalties';
import './services/selector';
import './services/staffchat';
import './services/names';
