type Category =
  | 'compacts'
  | 'sedans'
  | 'suvs'
  | 'coupes'
  | 'muscle'
  | 'sportsclassics'
  | 'sports'
  | 'super'
  | 'motorcycles'
  | 'offroad'
  | 'industrial'
  | 'utility'
  | 'vans'
  | 'cycles'
  | 'boats'
  | 'helicopters'
  | 'planes'
  | 'service'
  | 'emergency'
  | 'military'
  | 'commercial'
  | 'trains'
  | 'openwheel';

type CarClass = 'X' | 'S' | 'A+' | 'A' | 'B' | 'C' | 'D';
