INSERT INTO `items` (`name`, `label`, `weight`, `type`, `ammotype`, `stackable`, `useable`, `shouldClose`, `combinable`, `decayrate`, `image`, `description`) VALUES
('10kgoldchain', '10k Gold Chain', 2000, 'item', NULL, 0, 0, 1, NULL, NULL, '10kgoldchain.png', '10 carat golden chain'),
('acetone', 'Acetone', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'chemical2.png', 'Breathing moderate amounts for a short amount of time can irritate your nose, throat, lungs and eyes'),
('advancedlockpick', 'Advanced Lockpick', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'advancedlockpick.png', 'If you lose your keys a lot this is very useful... Also useful to open your beers'),
('advancedrepairkit', 'Advanced Repairkit', 4000, 'item', NULL, 0, 1, 1, NULL, NULL, 'advancedkit.png', 'A nice toolbox with stuff to repair your vehicle'),
('aluminum', 'Aluminium', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'aluminum.png', 'Nice piece of metal that you can probably use for something'),
('aluminumoxide', 'Aluminium Powder', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'aluminumoxide.png', 'Some powder to mix with'),
('antipatharia_coral', 'Antipatharia', 1000, 'item', NULL, 0, 0, 1, NULL, NULL, 'antipatharia_coral.png', 'Its also known as black corals or thorn corals'),
('armor', 'Armor', 5000, 'item', NULL, 0, 1, 1, NULL, NULL, 'armor.png', 'Some protection won\"t hurt... right?'),
('bandage', 'Bandage', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'bandage.png', 'A bandage works every time'),
('beer', 'Beer', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'beer.png', 'Nothing like a good cold beer!'),
('binoculars', 'Binoculars', 600, 'item', NULL, 0, 1, 1, NULL, NULL, 'binoculars.png', 'Sneaky Breaky...'),
('bluefish', 'Bluefish', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'bluefish.png', 'One fish two fish redfish...'),
('casinochips', 'Casino Chips', 0, 'item', NULL, 0, 0, 0, NULL, NULL, 'casinochips.png', 'Chips For Casino Gambling'),
('catfish', 'Catfish', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'catfish.png', 'A Catfish'),
('certificate', 'Certificate', 0, 'item', NULL, 0, 0, 1, NULL, NULL, 'certificate.png', 'Certificate that proves you own certain stuff'),
('cleaningkit', 'Cleaning Kit', 250, 'item', NULL, 0, 1, 1, NULL, NULL, 'cleaningkit.png', 'A microfiber cloth with some soap will let your car sparkle again!'),
('cocaleaf', 'Cocaine Leaf', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'cocaineleaf.png', 'Make that white girl'),
('coffee', 'Coffee', 200, 'item', NULL, 0, 1, 1, NULL, NULL, 'coffee.png', 'Pump 4 Caffeine'),
('cokebaggy', 'Bag of Coke', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'cocaine_baggy.png', 'To get happy real quick'),
('coke_brick', 'Coke Brick', 1000, 'item', NULL, 1, 0, 1, NULL, NULL, 'coke_brick.png', 'Heavy package of cocaine, mostly used for deals and takes a lot of space'),
('coke_small_brick', 'Coke Package', 350, 'item', NULL, 1, 0, 1, NULL, NULL, 'coke_small_brick.png', 'Small package of cocaine, mostly used for deals and takes a lot of space'),
('copper', 'Copper', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'copper.png', 'Nice piece of metal that you can probably use for something'),
('crack_baggy', 'Bag of Crack', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'crack_baggy.png', 'To get happy faster'),
('cryptostick', 'Crypto Stick', 200, 'item', NULL, 1, 1, 1, NULL, NULL, 'cryptostick.png', 'Why would someone ever buy money that doesn\"t exist.. How many would it contain..?'),
('dendrogyra_coral', 'Dendrogyra', 1000, 'item', NULL, 0, 0, 1, NULL, NULL, 'dendrogyra_coral.png', 'Its also known as pillar coral'),
('diamond_ring', 'Diamond Ring', 1500, 'item', NULL, 0, 0, 1, NULL, NULL, 'diamond_ring.png', 'A diamond ring seems like the jackpot to me!'),
('diving_gear', 'Diving Gear', 30000, 'item', NULL, 1, 1, 1, NULL, NULL, 'diving_gear.png', 'An oxygen tank and a rebreather'),
('drill', 'Drill', 20000, 'item', NULL, 0, 0, 0, NULL, NULL, 'drill.png', 'The real deal...'),
('driver_license', 'Drivers License', 0, 'item', NULL, 1, 1, 0, NULL, NULL, 'driver_license.png', 'Permit to show you can drive a vehicle'),
('electronickit', 'Electronic Kit', 100, 'item', NULL, 0, 1, 1, '{\n    \"accept\": [\"gatecrack\"],\n    \"reward\": \"trojan_usb\", \n    \"anim\": {\n        \"dict\": \"anim@amb@business@weed@weed_inspecting_high_dry@\", \n        \"lib\": \"weed_inspecting_high_base_inspector\", \n        \"text\": \"Making Trojan USB\", \n        \"timeOut\": 2000,\n    }\n}', NULL, 'electronickit.png', 'If you\"ve always wanted to build a robot you can maybe start here. Maybe you\"ll be the new Elon Musk?'),
('empty_evidence_bag', 'Empty Evidence Bag', 0, 'item', NULL, 0, 0, 0, NULL, NULL, 'evidence.png', 'Used a lot to keep DNA from blood, bullet shells and more'),
('empty_weed_bag', 'Empty Weed Bag', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'weed-empty-bag.png', 'A small empty bag'),
('ephedrine', 'Ephedrine', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'chemical1.png', 'Prescription medicine used to treat the symptoms of low blood pressure'),
('filled_evidence_bag', 'Evidence Bag', 200, 'item', NULL, 1, 0, 0, NULL, NULL, 'evidence.png', 'A filled evidence bag to see who committed the crime >:('),
('firework1', '2Brothers', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'firework1.png', 'Fireworks'),
('firework2', 'Poppelers', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'firework2.png', 'Fireworks'),
('firework3', 'WipeOut', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'firework3.png', 'Fireworks'),
('firework4', 'Weeping Willow', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'firework4.png', 'Fireworks'),
('firstaid', 'First Aid', 2500, 'item', NULL, 0, 1, 1, NULL, NULL, 'firstaid.png', 'You can use this First Aid kit to get people back on their feet'),
('fish', 'Fish', 1100, 'item', NULL, 0, 1, 1, NULL, NULL, 'fish.png', 'A normal fish Tatses pretty good!'),
('fishingbait', 'Fish Bait', 400, 'item', NULL, 0, 1, 1, NULL, NULL, 'fishbait.png', 'A fish bait'),
('fishingrod', 'Fishing Rod', 5000, 'item', NULL, 0, 1, 1, NULL, NULL, 'fishingrod.png', 'A fishing rod for adventures with friends!!'),
('fitbit', 'Fitbit', 500, 'item', NULL, 1, 1, 1, NULL, NULL, 'fitbit.png', 'I like fitbit'),
('gatecrack', 'Gatecrack', 0, 'item', NULL, 0, 0, 1, NULL, NULL, 'usb_device.png', 'Handy software to tear down some fences'),
('glass', 'Glass', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'glassplate.png', 'It is very fragile, watch out'),
('goldbar', 'Gold Bar', 7000, 'item', NULL, 0, 0, 1, NULL, NULL, 'goldbar.png', 'Looks pretty expensive to me'),
('goldchain', 'Golden Chain', 1500, 'item', NULL, 0, 0, 1, NULL, NULL, 'goldchain.png', 'A golden chain seems like the jackpot to me!'),
('goldfish', 'Goldfish', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'goldfish.png', 'A Goldfish... I wonder how he got there...'),
('grape', 'Grape', 100, 'item', NULL, 0, 1, 0, NULL, NULL, 'grape.png', 'Mmmmh yummie, grapes'),
('grapejuice', 'Grape Juice', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'grapejuice.png', 'Grape juice is said to be healthy'),
('handcuffs', 'Handcuffs', 100, 'item', NULL, 0, 1, 1, NULL, NULL, 'handcuffs.png', 'Comes in handy when people misbehave. Maybe it can be used for something else?'),
('harness', 'Race Harness', 1000, 'item', NULL, 1, 1, 1, NULL, NULL, 'harness.png', 'Racing Harness so no matter what you stay in the car'),
('heavyarmor', 'Heavy Armor', 5000, 'item', NULL, 0, 1, 1, NULL, NULL, 'armor.png', 'Some protection won\"t hurt... right?'),
('hydrochloricacid', 'Hydrochloric Acid', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'chemical1.png', 'Component of the gastric acid in the digestive systems of most animal species...including humans'),
('id_card', 'ID Card', 0, 'item', NULL, 1, 1, 0, NULL, NULL, 'id_card.png', 'A card containing all your information to identify yourself'),
('iphone', 'iPhone', 1000, 'item', NULL, 0, 0, 1, NULL, NULL, 'iphone.png', 'Very expensive phone'),
('iron', 'Iron', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'ironplate.png', 'Handy piece of metal that you can probably use for something'),
('ironoxide', 'Iron Powder', 100, 'item', NULL, 0, 0, 0, '{\n    \"accept\": [\"aluminumoxide\"], \n    \"reward\": \"thermite\", \n    \"anim\": {\n        \"dict\": \"anim@amb@business@weed@weed_inspecting_high_dry@\", \n        \"lib\": \"weed_inspecting_high_base_inspector\", \n        \"text\": \"Mixing powder..\", \n        \"timeOut\": 10000\n    }\n}', NULL, 'ironoxide.png', 'Some powder to mix with.'),
('jerry_can', 'Jerrycan 20L', 20000, 'item', NULL, 0, 1, 1, NULL, NULL, 'jerry_can.png', 'A can full of Fuel'),
('joint', 'Joint', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'joint.png', 'Sidney would be very proud at you'),
('killerwhalemeat', 'Killer Whale Meat', 1100, 'item', NULL, 0, 1, 1, NULL, NULL, 'killerwhalemeat.png', 'Meat cut from a Killer Whale'),
('kurkakola', 'Cola', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'cola.png', 'For all the thirsty out there'),
('labkey', 'Key', 500, 'item', NULL, 1, 1, 1, NULL, NULL, 'labkey.png', 'Key for a lock...?'),
('laptop', 'Laptop', 4000, 'item', NULL, 0, 0, 1, NULL, 86400, 'laptop.png', 'Expensive laptop'),
('largemouthbass', 'Largemouth Bass', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'largemouthbass.png', 'Fish for Fishing.'),
('lawyerpass', 'Lawyer Pass', 0, 'item', NULL, 1, 1, 0, NULL, NULL, 'lawyerpass.png', 'Pass exclusive to lawyers to show they can represent a suspect'),
('lighter', 'Lighter', 0, 'item', NULL, 0, 0, 1, NULL, NULL, 'lighter.png', 'On new years eve a nice fire to stand next to'),
('mastercard', 'Master Card', 0, 'item', NULL, 1, 1, 0, NULL, NULL, 'mastercard.png', 'MasterCard can be used via ATM'),
('metalscrap', 'Metal Scrap', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'metalscrap.png', 'You can probably make something nice out of this'),
('meth', 'Meth', 100, 'item', NULL, 0, 1, 1, NULL, NULL, 'meth10g.png', 'A baggie of Meth'),
('methtray', 'Meth Tray', 200, 'item', NULL, 0, 0, 0, NULL, NULL, 'methbrick.png', 'make some meth'),
('mg_ammo', 'MG ammo', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'mg_ammo.png', 'Ammo for Machine Guns'),
('moneybag', 'Money Bag', 0, 'item', NULL, 1, 1, 1, NULL, NULL, 'moneybag.png', 'A bag with cash'),
('nitrous', 'Nitrous', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'nitrous.png', 'Speed up, gas pedal! :D'),
('oxy', 'Prescription Oxy', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'oxy.png', 'The Label Has Been Ripped Off'),
('painkillers', 'Painkillers', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'painkillers.png', 'For pain you can\"t stand anymore, take this pill that\"d make you feel great again'),
('parachute', 'Parachute', 30000, 'item', NULL, 1, 1, 1, NULL, NULL, 'parachute.png', 'The sky is the limit! Woohoo!'),
('phone', 'Phone', 700, 'item', NULL, 1, 0, 0, NULL, NULL, 'phone.png', 'Neat phone ya got there'),
('pinger', 'Pinger', 1000, 'item', NULL, 0, 0, 1, NULL, NULL, 'pinger.png', 'With a pinger and your phone you can send out your location'),
('pistol_ammo', 'Pistol ammo', 200, 'item', NULL, 0, 1, 1, NULL, NULL, 'pistol_ammo.png', 'Ammo for Pistols'),
('plastic', 'Plastic', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'plastic.png', 'RECYCLE! - Greta Thunberg 2019'),
('police_stormram', 'Stormram', 18000, 'item', NULL, 0, 1, 1, NULL, NULL, 'police_stormram.png', 'A nice tool to break into doors'),
('printerdocument', 'Document', 500, 'item', NULL, 1, 1, 1, NULL, NULL, 'printerdocument.png', 'A nice document'),
('puremeth', 'Pure Meth', 100, 'item', NULL, 0, 1, 1, NULL, NULL, 'meth10g.png', 'A baggie of Pure Meth'),
('puremethtray', 'Pure Meth Tray', 200, 'item', NULL, 0, 0, 0, NULL, NULL, 'methbrick.png', 'make some meth'),
('radio', 'Radio', 2000, 'item', NULL, 1, 1, 1, NULL, NULL, 'radio.png', 'You can communicate with this through a signal'),
('radioscanner', 'Radio Scanner', 1000, 'item', NULL, 0, 0, 1, NULL, NULL, 'radioscanner.png', 'With this you can get some police alerts. Not 100% effective however'),
('redfish', 'Redfish', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'redfish.png', 'One fish two fish...'),
('repairkit', 'Repairkit', 2500, 'item', NULL, 0, 1, 1, NULL, NULL, 'repairkit.png', 'A nice toolbox with stuff to repair your vehicle'),
('rifle_ammo', 'Rifle ammo', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'rifle_ammo.png', 'Ammo for Rifles'),
('rolex', 'Golden Watch', 1500, 'item', NULL, 0, 0, 1, NULL, NULL, 'rolex_watch.png', 'A golden watch seems like the jackpot to me!'),
('rolling_paper', 'Rolling Paper', 0, 'item', NULL, 0, 0, 1, '{\n    \"accept\": {\"weed_white-widow\", \"weed_skunk\", \"weed_purple-haze\", \"weed_og-kush\", \"weed_amnesia\", \"weed_ak47\"}, \n    \"reward\": \"joint\", \n    \"anim\": {\n        \"dict\": \"anim@amb@business@weed@weed_inspecting_high_dry@\", \n        \"lib\": \"weed_inspecting_high_base_inspector\", \n        \"text\": \"Rolling joint\", \n        \"timeOut\": 5000,\n    }\n}', NULL, 'rolling_paper.png', 'Paper made specifically for encasing and smoking tobacco or cannabis.'),
('rubber', 'Rubber', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'rubber.png', 'Rubber, I believe you can make your own rubber ducky with it :D'),
('salmon', 'Salmon', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'salmon.png', 'A Salmon Fish'),
('samsungphone', 'Samsung S10', 1000, 'item', NULL, 0, 0, 1, NULL, NULL, 'samsungphone.png', 'Very expensive phone'),
('sandwich', 'Sandwich', 200, 'item', NULL, 0, 1, 1, NULL, 1, 'sandwich.png', 'Nice bread for your stomach'),
('screwdriverset', 'Toolkit', 1000, 'item', NULL, 0, 0, 0, NULL, NULL, 'screwdriverset.png', 'Very useful to screw... screws...'),
('security_card_01', 'Security Card A', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'security_card_01.png', 'A security card... I wonder what it goes to'),
('security_card_02', 'Security Card B', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'security_card_02.png', 'A security card... I wonder what it goes to'),
('shotgun_ammo', 'Shotgun ammo', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'shotgun_ammo.png', 'Ammo for Shotguns'),
('smg_ammo', 'SMG ammo', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'smg_ammo.png', 'Ammo for Sub Machine Guns'),
('snikkel_candy', 'Snikkel', 100, 'item', NULL, 0, 1, 1, NULL, NULL, 'snikkel_candy.png', 'Some delicious candy :O'),
('snowball', 'Snowball', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'snowball.png', 'Should have catched it :D'),
('sniper_ammo', 'Sniper ammo', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'snp_ammo.png', 'Ammo for Sniper Rifles'),
('snspistol_part_1', 'SNS Loop', 1500, 'item', NULL, 1, 0, 1, NULL, NULL, 'snspistol_part_1.png', 'Loop of a SNS Pistol'),
('snspistol_part_2', 'SNS Trigger', 1500, 'item', NULL, 1, 0, 1, NULL, NULL, 'snspistol_part_2.png', 'Trigger of a SNS Pistol'),
('snspistol_part_3', 'SNS Clip', 1500, 'item', NULL, 1, 0, 1, '{\n    \"accept\": {\"snspistol_part_1\"}, \n    \"reward\": \"snspistol_stage_1\", \n    \"anim\": {\n        \"dict\": \"anim@amb@business@weed@weed_inspecting_high_dry@\", \n        \"lib\": \"weed_inspecting_high_base_inspector\", \n        \"text\": \"Atttaching attachments\", \n        \"timeOut\": 15000,\n    }\n}', NULL, 'snspistol_part_3.png', 'Clip of a SNS Pistol'),
('snspistol_stage_1', 'SNS Body', 2500, 'item', NULL, 1, 0, 1, '{\n    \"accept\": {\"snspistol_part_2\"}, \n    \"reward\": \"weapon_snspistol\", \n    \"anim\": {\n        \"dict\": \"anim@amb@business@weed@weed_inspecting_high_dry@\", \n        \"lib\": \"weed_inspecting_high_base_inspector\", \n        \"text\": \"Attaching attachments\", \n        \"timeOut\": 15000,\n    }\n}', NULL, 'snspistol_stage_1.png', 'SNS w/ Loop & Clip'),
('steel', 'Steel', 100, 'item', NULL, 0, 0, 0, NULL, NULL, 'steel.png', 'Nice piece of metal that you can probably use for something'),
('stickynote', 'Sticky note', 0, 'item', NULL, 1, 0, 0, NULL, NULL, 'stickynote.png', 'Sometimes handy to remember something :)'),
('stingraymeat', 'Stingray Meat', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'stingraymeat.png', 'Stingray Meat'),
('stripedbass', 'Striped Bass', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'stripedbass.png', 'A Striped Bass'),
('tablet', 'Tablet', 2000, 'item', NULL, 0, 0, 1, NULL, NULL, 'tablet.png', 'Expensive tablet'),
('thermite', 'Thermite', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'thermite.png', 'Sometimes you\"d wish for everything to burn'),
('tigersharkmeat', 'Tigershark Meat', 1111, 'item', NULL, 0, 1, 1, NULL, NULL, 'tigersharkmeat.png', 'Meat cut from a Tigershark'),
('tosti', 'Grilled Cheese Sandwich', 200, 'item', NULL, 0, 1, 1, NULL, NULL, 'tosti.png', 'Nice to eat'),
('trojan_usb', 'Trojan USB', 0, 'item', NULL, 0, 0, 1, NULL, NULL, 'usb_device.png', 'Handy software to shut down some systems'),
('tunerlaptop', 'Tunerchip', 2000, 'item', NULL, 1, 1, 1, NULL, NULL, 'tunerlaptop.png', 'With this tunerchip you can get your car on steroids... If you know what you\"re doing'),
('twerks_candy', 'Twerks', 100, 'item', NULL, 0, 1, 1, NULL, NULL, 'twerks_candy.png', 'Some delicious candy :O'),
('visa', 'Visa Card', 0, 'item', NULL, 1, 1, 0, NULL, NULL, 'visacard.png', 'Visa can be used via ATM'),
('vodka', 'Vodka', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'vodka.png', 'For all the thirsty out there'),
('walkstick', 'Walking Stick', 1000, 'item', NULL, 0, 1, 1, NULL, NULL, 'walkstick.png', 'Walking stick for ya\"ll grannies out there.. HAHA'),
('water_bottle', 'Bottle of Water', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'water_bottle.png', 'For all the thirsty out there'),
('weaponlicense', 'Weapon License', 0, 'item', NULL, 1, 1, 1, NULL, NULL, 'weapon_license.png', 'Weapon License'),
('weapon_advancedrifle', 'Advanced Rifle', 1000, 'weapon', 'AMMO_RIFLE', 1, 0, NULL, NULL, NULL, 'weapon_advancedrifle.png', 'An assault version of a rapid-fire, magazine-fed automatic rifle designed for infantry use'),
('weapon_appistol', 'AP Pistol', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_appistol.png', 'A small firearm designed to be held in one hand that is automatic'),
('weapon_assaultrifle', 'Assault Rifle', 1000, 'weapon', 'AMMO_RIFLE', 1, 0, NULL, NULL, NULL, 'weapon_assaultrifle.png', 'A rapid-fire, magazine-fed automatic rifle designed for infantry use'),
('weapon_assaultrifle_mk2', 'AK-47 MK2', 1000, 'weapon', 'AMMO_RIFLE', 1, 1, NULL, NULL, NULL, 'assaultriflemk2.png', 'Assault Rifle MK2'),
('weapon_assaultshotgun', 'Assault Shotgun', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 0, NULL, NULL, NULL, 'weapon_assaultshotgun.png', 'An assault version of asmoothbore gun for firing small shot at short range'),
('weapon_assaultsmg', 'Assault SMG', 1000, 'weapon', 'AMMO_SMG', 1, 0, NULL, NULL, NULL, 'weapon_assaultsmg.png', 'An assault version of a handheld lightweight machine gun'),
('weapon_autoshotgun', 'Auto Shotgun', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 0, NULL, NULL, NULL, 'weapon_autoshotgun.png', 'A shotgun capable of rapid continous fire'),
('weapon_ball', 'Ball', 1000, 'weapon', 'AMMO_BALL', 1, 0, NULL, NULL, NULL, 'weapon_ball.png', 'A solid or hollow spherical or egg-shaped object that is kicked, thrown, or hit in a game'),
('weapon_bat', 'Bat', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_bat.png', 'Used for hitting a ball in sports (or other things)'),
('weapon_battleaxe', 'Battle Axe', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_battleaxe.png', 'A large broad-bladed axe used in ancient warfare'),
('weapon_bottle', 'Broken Bottle', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_bottle.png', 'A broken bottle'),
('weapon_bread', 'Baquette', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'baquette.png', 'Bread...?'),
('weapon_briefcase', 'Briefcase', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_briefcase.png', 'A briefcase for storing important documents'),
('weapon_briefcase_02', 'Suitcase', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_briefcase2.png', 'Wonderfull for nice vacation to Liberty City'),
('weapon_bullpuprifle', 'Bullpup Rifle', 1000, 'weapon', 'AMMO_RIFLE', 1, 0, NULL, NULL, NULL, 'weapon_bullpuprifle.png', 'A compact automatic assault rifle'),
('weapon_bullpuprifle_mk2', 'Bull Puprifle MK2', 1000, 'weapon', 'AMMO_RIFLE', 1, 1, NULL, NULL, NULL, 'bullpuprifle_mk2.png', 'Bull Puprifle MK2'),
('weapon_bullpupshotgun', 'Bullpup Shotgun', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 0, NULL, NULL, NULL, 'weapon_bullpupshotgun.png', 'A compact smoothbore gun for firing small shot at short range'),
('weapon_bzgas', 'BZ Gas', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_bzgas.png', 'A cannister of gas that causes extreme pain'),
('weapon_carbinerifle', 'Carbine Rifle', 1000, 'weapon', 'AMMO_RIFLE', 1, 0, NULL, NULL, NULL, 'weapon_carbinerifle.png', 'A lightweight automatic rifle'),
('weapon_carbinerifle_mk2', 'PD 762', 1000, 'weapon', 'AMMO_RIFLE', 1, 1, NULL, NULL, NULL, 'carbineriflemk2.png', 'Carbine Rifle MK2'),
('weapon_ceramicpistol', 'Weapon Ceramicpistol', 1000, 'weapon', 'AMMO_PISTOL', 1, 1, NULL, NULL, NULL, 'weapon_ceramicpistol.png', 'Weapon Ceramicpistol'),
('weapon_combatmg', 'Combat MG', 1000, 'weapon', 'AMMO_MG', 1, 0, NULL, NULL, NULL, 'weapon_combatmg.png', 'A combat version of an automatic gun that fires bullets in rapid succession for as long as the trigger is pressed'),
('weapon_combatmg_mk2', 'Weapon Combatmg MK2', 1000, 'weapon', 'AMMO_MG', 1, 1, NULL, NULL, NULL, 'combatmg_mk2.png', 'Weapon Combatmg MK2'),
('weapon_combatpdw', 'Combat PDW', 1000, 'weapon', 'AMMO_SMG', 1, 0, NULL, NULL, NULL, 'weapon_combatpdw.png', 'A combat version of a handheld lightweight machine gun'),
('weapon_combatpistol', 'Combat Pistol', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_combatpistol.png', 'A combat version small firearm designed to be held in one hand'),
('weapon_combatshotgun', 'Weapon Combatshotgun', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 1, NULL, NULL, NULL, 'combatshotgun.png', 'Weapon Combatshotgun'),
('weapon_compactlauncher', 'Compact Launcher', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_compactlauncher.png', 'A compact grenade launcher'),
('weapon_compactrifle', 'Compact Rifle', 1000, 'weapon', 'AMMO_RIFLE', 1, 0, NULL, NULL, NULL, 'weapon_compactrifle.png', 'A compact version of an assault rifle'),
('weapon_crowbar', 'Crowbar', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_crowbar.png', 'An iron bar with a flattened end, used as a lever'),
('weapon_dagger', 'Dagger', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_dagger.png', 'A short knife with a pointed and edged blade, used as a weapon'),
('weapon_dbshotgun', 'Double-barrel Shotgun', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 0, NULL, NULL, NULL, 'weapon_dbshotgun.png', 'A shotgun with two parallel barrels, allowing two single shots to be fired in quick succession'),
('weapon_doubleaction', 'Double Action Revolver', 1000, 'weapon', 'AMMO_PISTOL', 1, 1, NULL, NULL, NULL, 'doubleaction.png', 'Double Action Revolver'),
('weapon_fireextinguisher', 'Fire Extinguisher', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_fireextinguisher.png', 'A portable device that discharges a jet of water, foam, gas, or other material to extinguish a fire'),
('weapon_firework', 'Firework Launcher', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_firework.png', 'A device containing gunpowder and other combustible chemicals that causes a spectacular explosion when ignited'),
('weapon_flare', 'Flare pistol', 1000, 'weapon', 'AMMO_FLARE', 1, 0, NULL, NULL, NULL, 'weapon_flare.png', 'A small pyrotechnic devices used for illumination and signalling'),
('weapon_flaregun', 'Flare Gun', 1000, 'weapon', 'AMMO_FLARE', 1, 0, NULL, NULL, NULL, 'weapon_flaregun.png', 'A handgun for firing signal rockets'),
('weapon_flashlight', 'Flashlight', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_flashlight.png', 'A battery-operated portable light'),
('weapon_gadgetpistol', 'Weapon Gadgetpistol', 1000, 'weapon', 'AMMO_PISTOL', 1, 1, NULL, NULL, NULL, 'weapon_gadgetpistol.png', 'Weapon Gadgetpistol'),
('weapon_garbagebag', 'Garbage Bag', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_garbagebag.png', 'A garbage bag'),
('weapon_golfclub', 'Golfclub', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_golfclub.png', 'A club used to hit the ball in golf'),
('weapon_grenade', 'Grenade', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_grenade.png', 'A handheld throwable bomb'),
('weapon_grenadelauncher', 'Grenade Launcher', 1000, 'weapon', 'AMMO_GRENADELAUNCHER', 1, 0, NULL, NULL, NULL, 'weapon_grenadelauncher.png', 'A weapon that fires a specially-designed large-caliber projectile, often with an explosive, smoke or gas warhead'),
('weapon_grenadelauncher_smoke', 'Smoke Grenade Launcher', 1000, 'weapon', 'AMMO_GRENADELAUNCHER', 1, 0, NULL, NULL, NULL, 'weapon_smokegrenade.png', 'A bomb that produces a lot of smoke when it explodes'),
('weapon_gusenberg', 'Thompson SMG', 1000, 'weapon', 'AMMO_MG', 1, 0, NULL, NULL, NULL, 'weapon_gusenberg.png', 'An automatic rifle commonly referred to as a tommy gun'),
('weapon_hammer', 'Hammer', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_hammer.png', 'Used for jobs such as breaking things (legs) and driving in nails'),
('weapon_handcuffs', 'Handcuffs', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_handcuffs.png', 'A pair of lockable linked metal rings for securing a prisoner\"s wrists'),
('weapon_hatchet', 'Hatchet', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_hatchet.png', 'A small axe with a short handle for use in one hand'),
('weapon_hazardcan', 'Weapon Hazardcan', 1000, 'weapon', 'AMMO_PETROLCAN', 1, 1, NULL, NULL, NULL, 'weapon_hazardcan.png', 'Weapon Hazardcan'),
('weapon_heavypistol', 'Heavy Pistol', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_heavypistol.png', 'A hefty firearm designed to be held in one hand (or attempted)'),
('weapon_heavyshotgun', 'Heavy Shotgun', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 0, NULL, NULL, NULL, 'weapon_heavyshotgun.png', 'A large smoothbore gun for firing small shot at short range'),
('weapon_heavysniper', 'Heavy Sniper', 1000, 'weapon', 'AMMO_SNIPER', 1, 0, NULL, NULL, NULL, 'weapon_heavysniper.png', 'An upgraded high-precision, long-range rifle'),
('weapon_heavysniper_mk2', 'Weapon Heavysniper MK2', 1000, 'weapon', 'AMMO_SNIPER', 1, 1, NULL, NULL, NULL, 'heavysniper_mk2.png', 'Weapon Heavysniper MK2'),
('weapon_hominglauncher', 'Homing Launcher', 1000, 'weapon', 'AMMO_STINGER', 1, 0, NULL, NULL, NULL, 'weapon_hominglauncher.png', 'A weapon fitted with an electronic device that enables it to find and hit a target'),
('weapon_knife', 'Knife', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_knife.png', 'An instrument composed of a blade fixed into a handle, used for cutting or as a weapon'),
('weapon_knuckle', 'Knuckle', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_knuckle.png', 'A metal guard worn over the knuckles in fighting, especially to increase the effect of the blows'),
('weapon_machete', 'Machete', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_machete.png', 'A broad, heavy knife used as a weapon'),
('weapon_machinepistol', 'Tec-9', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_machinepistol.png', 'A self-loading pistol capable of burst or fully automatic fire'),
('weapon_marksmanrifle', 'Marksman Rifle', 1000, 'weapon', 'AMMO_SNIPER', 1, 0, NULL, NULL, NULL, 'weapon_marksmanrifle.png', 'A very accurate single-fire rifle'),
('weapon_marksmanrifle_mk2', 'Weapon Marksmanrifle MK2', 1000, 'weapon', 'AMMO_SNIPER', 1, 1, NULL, NULL, NULL, 'marksmanrifle_mk2.png', 'Weapon Marksmanrifle MK2'),
('weapon_mg', 'Machinegun', 1000, 'weapon', 'AMMO_MG', 1, 0, NULL, NULL, NULL, 'weapon_mg.png', 'An automatic gun that fires bullets in rapid succession for as long as the trigger is pressed'),
('weapon_microsmg', 'Micro SMG', 1000, 'weapon', 'AMMO_SMG', 1, 0, NULL, NULL, NULL, 'weapon_microsmg.png', 'A handheld lightweight machine gun'),
('weapon_militaryrifle', 'Weapon Militaryrifle', 1000, 'weapon', 'AMMO_RIFLE', 1, 1, NULL, NULL, NULL, 'militaryrifle.png', 'Weapon Militaryrifle'),
('weapon_minigun', 'Minigun', 1000, 'weapon', 'AMMO_MINIGUN', 1, 0, NULL, NULL, NULL, 'weapon_minigun.png', 'A portable machine gun consisting of a rotating cluster of six barrels and capable of variable rates of fire of up to 6,000 rounds per minute'),
('weapon_minismg', 'Mini SMG', 1000, 'weapon', 'AMMO_SMG', 1, 0, NULL, NULL, NULL, 'weapon_minismg.png', 'A mini handheld lightweight machine gun'),
('weapon_molotov', 'Molotov', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_molotov.png', 'A crude bomb made of a bottle filled with a flammable liquid and fitted with a wick for lighting'),
('weapon_musket', 'Musket', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 0, NULL, NULL, NULL, 'weapon_musket.png', 'An infantryman\"s light gun with a long barrel, typically smooth-bored, muzzleloading, and fired from the shoulder'),
('weapon_navyrevolver', 'Weapon Navyrevolver', 1000, 'weapon', 'AMMO_PISTOL', 1, 1, NULL, NULL, NULL, 'weapon_navyrevolver.png', 'Weapon Navyrevolver'),
('weapon_nightstick', 'Nightstick', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_nightstick.png', 'A police officer\"s club or billy'),
('weapon_petrolcan', 'Petrol Can', 1000, 'weapon', 'AMMO_PETROLCAN', 1, 0, NULL, NULL, NULL, 'weapon_petrolcan.png', 'A robust liquid container made from pressed steel'),
('weapon_pipebomb', 'Pipe Bomb', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_pipebomb.png', 'A homemade bomb, the components of which are contained in a pipe'),
('weapon_pistol', 'Walther P99', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_pistol.png', 'A small firearm designed to be held in one hand'),
('weapon_pistol50', 'Pistol .50 Cal', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_pistol50.png', 'A .50 caliber firearm designed to be held with both hands'),
('weapon_pistol_mk2', 'Pistol Mk II', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_pistol_mk2.png', 'An upgraded small firearm designed to be held in one hand'),
('weapon_poolcue', 'Poolcue', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_poolcue.png', 'A stick used to strike a ball, usually the cue ball (or other things)'),
('weapon_proxmine', 'Proxmine Grenade', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_proximitymine.png', 'A bomb placed on the ground that detonates when going within its proximity'),
('weapon_pumpshotgun', 'Pump Shotgun', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 0, NULL, NULL, NULL, 'weapon_pumpshotgun.png', 'A pump-action smoothbore gun for firing small shot at short range'),
('weapon_pumpshotgun_mk2', 'Pumpshotgun MK2', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 1, NULL, NULL, NULL, 'pumpshotgun_mk2.png', 'Pumpshotgun MK2'),
('weapon_railgun', 'Railgun', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_railgun.png', 'A weapon that uses electromagnetic force to launch high velocity projectiles'),
('weapon_raycarbine', 'Weapon Raycarbine', 1000, 'weapon', 'AMMO_SMG', 1, 1, NULL, NULL, NULL, 'weapon_raycarbine.png', 'Weapon Raycarbine'),
('weapon_rayminigun', 'Weapon Rayminigun', 1000, 'weapon', 'AMMO_MINIGUN', 1, 1, NULL, NULL, NULL, 'weapon_rayminigun.png', 'Weapon Rayminigun'),
('weapon_raypistol', 'Weapon Raypistol', 1000, 'weapon', 'AMMO_PISTOL', 1, 1, NULL, NULL, NULL, 'weapon_raypistol.png', 'Weapon Raypistol'),
('weapon_remotesniper', 'Remote Sniper', 1000, 'weapon', 'AMMO_SNIPER_REMOTE', 1, 0, NULL, NULL, NULL, 'weapon_remotesniper.png', 'A portable high-precision, long-range rifle'),
('weapon_revolver', 'Revolver', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_revolver.png', 'A pistol with revolving chambers enabling several shots to be fired without reloading'),
('weapon_revolver_mk2', 'Violence', 1000, 'weapon', 'AMMO_PISTOL', 1, 1, NULL, NULL, NULL, 'revolvermk2.png', 'da Violence'),
('weapon_rpg', 'RPG', 1000, 'weapon', 'AMMO_RPG', 1, 0, NULL, NULL, NULL, 'weapon_rpg.png', 'A rocket-propelled grenade launcher'),
('weapon_sawnoffshotgun', 'Sawn-off Shotgun', 1000, 'weapon', 'AMMO_SHOTGUN', 1, 0, NULL, NULL, NULL, 'weapon_sawnoffshotgun.png', 'A sawn-off smoothbore gun for firing small shot at short range'),
('weapon_smg', 'SMG', 1000, 'weapon', 'AMMO_SMG', 1, 0, NULL, NULL, NULL, 'weapon_smg.png', 'A handheld lightweight machine gun'),
('weapon_smg_mk2', 'PD MP5 2', 1000, 'weapon', 'AMMO_SMG', 1, 1, NULL, NULL, NULL, 'smg.png', 'SMG MK2'),
('weapon_smokegrenade', 'Smoke Grenade', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_c4.png', 'An explosive charge that can be remotely detonated'),
('weapon_sniperrifle', 'Sniper Rifle', 1000, 'weapon', 'AMMO_SNIPER', 1, 0, NULL, NULL, NULL, 'weapon_sniperrifle.png', 'A high-precision, long-range rifle'),
('weapon_snowball', 'Snowball', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_snowball.png', 'A ball of packed snow, especially one made for throwing at other people for fun'),
('weapon_snspistol', 'SNS Pistol', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_snspistol.png', 'A very small firearm designed to be easily concealed'),
('weapon_snspistol_mk2', 'SNS Pistol MK2', 1000, 'weapon', 'AMMO_PISTOL', 1, 1, NULL, NULL, NULL, 'snspistol_mk2.png', 'SNS Pistol MK2'),
('weapon_specialcarbine', 'Special Carbine', 1000, 'weapon', 'AMMO_RIFLE', 1, 0, NULL, NULL, NULL, 'weapon_specialcarbine.png', 'An extremely versatile assault rifle for any combat situation'),
('weapon_specialcarbine_mk2', 'Weapon Wpecialcarbine MK2', 1000, 'weapon', 'AMMO_RIFLE', 1, 1, NULL, NULL, NULL, 'specialcarbine_mk2.png', 'Weapon Wpecialcarbine MK2'),
('weapon_stickybomb', 'C4', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_stickybomb.png', 'An explosive charge covered with an adhesive that when thrown against an object sticks until it explodes'),
('weapon_stone_hatchet', 'Weapon Stone Hatchet', 1000, 'weapon', NULL, 1, 1, NULL, NULL, NULL, 'stone_hatchet.png', 'Stone ax'),
('weapon_stungun', 'Taser', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_stungun.png', 'A weapon firing barbs attached by wires to batteries, causing temporary paralysis'),
('weapon_switchblade', 'Switchblade', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_switchblade.png', 'A knife with a blade that springs out from the handle when a button is pressed'),
('weapon_unarmed', 'Fists', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'placeholder.png', 'Fisticuffs'),
('weapon_vintagepistol', 'Vintage Pistol', 1000, 'weapon', 'AMMO_PISTOL', 1, 0, NULL, NULL, NULL, 'weapon_vintagepistol.png', 'An antique firearm designed to be held in one hand'),
('weapon_wrench', 'Wrench', 1000, 'weapon', NULL, 1, 0, NULL, NULL, NULL, 'weapon_wrench.png', 'A tool used for gripping and turning nuts, bolts, pipes, etc'),
('weed_ak47', 'AK47 2g', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'weed-baggie.png', 'A weed bag with 2g AK47'),
('weed_ak47_seed', 'AK47 Seed', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'weed-plant-seed.png', 'A weed seed of AK47'),
('weed_amnesia', 'Amnesia 2g', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'weed-baggie.png', 'A weed bag with 2g Amnesia'),
('weed_amnesia_seed', 'Amnesia Seed', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'weed-plant-seed.png', 'A weed seed of Amnesia'),
('weed_brick', 'Weed Brick', 1000, 'item', NULL, 0, 0, 1, NULL, NULL, 'weed_brick.png', '1KG Weed Brick to sell to large customers.'),
('weed_nutrition', 'Plant Fertilizer', 2000, 'item', NULL, 0, 1, 1, NULL, NULL, 'weed_nutrition.png', 'Plant nutrition'),
('weed_og-kush', 'OGKush 2g', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'weed-baggie.png', 'A weed bag with 2g OG Kush'),
('weed_og-kush_seed', 'OGKush Seed', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'weed-plant-seed.png', 'A weed seed of OG Kush'),
('weed_purple-haze', 'Purple Haze 2g', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'weed-baggie.png', 'A weed bag with 2g Purple Haze'),
('weed_purple-haze_seed', 'Purple Haze Seed', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'weed-plant-seed.png', 'A weed seed of Purple Haze'),
('weed_skunk', 'Skunk 2g', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'weed-baggie.png', 'A weed bag with 2g Skunk'),
('weed_skunk_seed', 'Skunk Seed', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'weed-plant-seed.png', 'A weed seed of Skunk'),
('weed_white-widow', 'White Widow 2g', 200, 'item', NULL, 0, 1, 0, NULL, NULL, 'weed-baggie.png', 'A weed bag with 2g White Widow'),
('weed_white-widow_seed', 'White Widow Seed', 0, 'item', NULL, 0, 1, 0, NULL, NULL, 'weed-plant-seed.png', 'A weed seed of White Widow'),
('whiskey', 'Whiskey', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'whiskey.png', 'For all the thirsty out there');
INSERT INTO `items` (`name`, `label`, `weight`, `type`, `ammotype`, `stackable`, `useable`, `shouldClose`, `combinable`, `decayrate`, `image`, `description`) VALUES
('wine', 'Wine', 300, 'item', NULL, 0, 1, 0, NULL, NULL, 'wine.png', 'Some good wine to drink on a fine evening'),
('xtcbaggy', 'Bag of XTC', 0, 'item', NULL, 0, 1, 1, NULL, NULL, 'xtc_baggy.png', 'Pop those pills baby'),

('pistol_extendedclip', 'Pistol Extended Clip', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_extendedclip.png', 'Extended clip voor elke soort pistol.'),
('smg_extendedclip', 'SMG Extended Clip', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_extendedclip.png', 'Extended clip voor elke soort SMG.'),
('shotgun_extendedclip', 'Shotgun Extended Clip', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_extendedclip.png', 'Extended clip voor elke soort shotgun.'),
('rifle_extendedclip', 'Rifle Extended Clip', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_extendedclip.png', 'Extended clip voor elke soort rifle.'),
('mg_extendedclip', 'Machinegun Extended Clip', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_extendedclip.png', 'Extended clip voor elke soort machinegun.'),
('sniper_extendedclip', 'Sniper Extended Clip', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_extendedclip.png', 'Extended clip voor elke soort sniper.'),
('luxuryfinish', 'Luxury Finish', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_extendedclip.png', 'Luxury Finish voor je wapen.'),
('grip', 'Wapen Grip', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_suppressor.png', 'Grip voor je wapen.'),
('flashlight', 'Wapen Flashlight', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_flashlight.png', 'Flashlight voor je wapen.'),
('pistol_suppressor', 'Pistol Suppressor', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_suppressor.png', 'Suppressor voor elke soort pistol.'),
('smg_suppressor', 'SMG Suppressor', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_suppressor.png', 'Suppressor voor elke soort SMG.'),
('shotgun_suppressor', 'Shotgun Suppressor', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_suppressor.png', 'Suppressor voor elke soort shotgun.'),
('rifle_suppressor', 'Rifle Suppressor', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_suppressor.png', 'Suppressor voor elke soort rifle.'),
('sniper_suppressor', 'Sniper Suppressor', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'pistol_suppressor.png', 'Suppressor voor elke soort sniper.'),
('smg_scope', 'SMG Scope', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'smg_scope.png', 'Scope voor elke soort SMG.'),
('rifle_scope', 'Rifle Scope', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'smg_scope.png', 'Scope voor elke soort rifle.'),
('sniper_scope', 'Sniper Scope', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'smg_scope.png', 'Scope voor elke soort sniper.'),
('smg_drum', 'SMG Drummag', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'rifle_drummag.png', 'Drummag voor elke soort SMG.'),
('shotgun_drum', 'Shotgun Drummag', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'rifle_drummag.png', 'Drummag voor elke soort shotgun.'),
('rifle_drum', 'Rifle Drummag', 1000, 'item', NULL, 0, 1, 1, NULL, 86400, 'rifle_drummag.png', 'Drummag voor elke soort rifle.'),
('moneyroll', 'Geldrolletje', 100, 'item', NULL, 1, 0, 1, NULL, NULL, 'markedbills.png', 'Een rolletje met briefjes.'),
('markedbills', 'Zak geld', 1000, 'item', NULL, 1, 0, 1, NULL, NULL, 'markedbills.png', 'Een zak vol briefjes.'),
('inkedbills', 'Zak geinkt geld', 2000, 'item', NULL, 1, 0, 1, NULL, NULL, 'markedbills.png', 'Een zak vol briefjes met inkt.'),
('lockpick', 'Lockpick', 500, 'item', NULL, 0, 1, 1, NULL, NULL, 'lockpick.png', 'Voor als je de sleutels kwijt bent.'),
;